######################## default configuration ####################
baseURL = ""
languageCode = "en-us"
title = "The Bang App"
theme = "influencer-hugo"
summaryLength = "10"
paginate = 6

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "Home"
  URL = "banner"
  weight = 1
  
  [[menu.main]]
  name = "Features"
  URL = "service"
  weight = 2
  
  [[menu.main]]
  name = "Get early access"
  URL = "quote"
  weight = 3
  



#################### default parameters ################################
[params]
logo = ""
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# copyright
copyright = "Copyright &copy; 2019 [GetHugoThemes](https://gethugothemes.com) All Rights Reserved"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.navButton]
enable = true

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# Footer ########################
[params.footer]
content = "Learn how Tree of Wally funnels $100B annual digital ad spend to  citizens of the internet"


############################# post share ###################
[[params.share]]
title = "Instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/thebangapp/"